#!/bin/sh
# Expected to be called as: depmodwrapper -{a,A} KERNEL_VERSION
if [ \( "$1" != "-a" -a "$1" != "-A" \) -o "$2" != "-b" ]; then
    echo "Usage: depmodwrapper -{a,A} -b rootfs KERNEL_VERSION" >&2
    exit 1
fi
if [ ! -r /mnt/target-kernel/System.map-$4 ]; then
    echo "Unable to read: /mnt/target-kernel/System.map-$4" >&2
    exec env depmod "$1" "$2" "$3" "$4"
else
    exec env depmod "$1" "$2" "$3" -F "/mnt/target-kernel/System.map-$4" "$4"
fi

